services:
  - type: web
    name: kimpga-app
    env: node
    buildCommand: npm run build:client
    startCommand: node server/push-server.js
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - client/**
        - server/**
        - package.json
        - render.yaml 